branches:
  only:
    - master
language: node_js
cache:
  directories:
    - 'node_modules'
install:
  - npm install
  - npm install -g codecov
script:
  - npm run lint
  - npm test
  - npm run build
  - codecov
