const ENABLE_AUTO_RELOAD = 'ENABLE_AUTO_RELOAD';
const DISABLE_AUTO_RELOAD = 'DISABLE_AUTO_RELOAD';
const SET_CURRENCY = 'SET_CURRENCY';

export { ENABLE_AUTO_RELOAD, DISABLE_AUTO_RELOAD, SET_CURRENCY };
