const FETCH_ZRX_PRICE = 'FETCH_ZRX_PRICE';
const FETCH_ZRX_PRICE_FAILED = 'FETCH_ZRX_PRICE_FAILED';
const FETCH_ZRX_PRICE_SUCCEEDED = 'FETCH_ZRX_PRICE_SUCCEEDED';

const fetchZrxPrice = currency => ({
  type: FETCH_ZRX_PRICE,
  currency,
});

export {
  FETCH_ZRX_PRICE,
  FETCH_ZRX_PRICE_FAILED,
  FETCH_ZRX_PRICE_SUCCEEDED,
  fetchZrxPrice,
};
