const FETCH_RELAYERS = 'FETCH_RELAYERS';
const FETCH_RELAYERS_FAILED = 'FETCH_RELAYERS_FAILED';
const FETCH_RELAYERS_SUCCEEDED = 'FETCH_RELAYERS_SUCCEEDED';

const fetchRelayers = () => ({
  type: FETCH_RELAYERS,
});

export {
  FETCH_RELAYERS,
  FETCH_RELAYERS_FAILED,
  FETCH_RELAYERS_SUCCEEDED,
  fetchRelayers,
};
